GET https://sleepy-headland-54109.herokuapp.com/data

###

GET https://sleepy-headland-54109.herokuapp.com/

###
GET https://sleepy-headland-54109.herokuapp.com/data/81

###
POST https://sleepy-headland-54109.herokuapp.com/data
Content-Type: application/json

{
    "propietario": "Juan",
    "marca": "Seat",
    "modelo": "Leon",
    "matricula": "8888NNN"
}

###
PUT https://sleepy-headland-54109.herokuapp.com/data/111
Content-Type: application/json

{
    "propietario": "Juan",
    "marca": "Cupra",
    "modelo": "Leon",
    "matricula": "8888NNN"
}

###
DELETE https://sleepy-headland-54109.herokuapp.com/data/81

